# Generated by Django 3.1.3 on 2020-12-01 16:42

from django.db import migrations, models
import resources.models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20201110_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='passport',
            field=models.FileField(upload_to='private/documents', validators=[resources.models.is_zip_validator]),
        ),
    ]
